name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test

      - name: Test Images
        run: make testdata

  build-deploy-wasm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Install clang
        run: sudo apt-get update && sudo apt-get install -y clang

      - name: Build WebAssembly
        run: make wasm

      - name: Prepare Pages content
        run: |
          mkdir -p _site
          cp examples/wasm/grayskull.wasm _site/
          cp examples/wasm/*.html _site/
          cp examples/wasm/*.js _site/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
